### ISSUE TITLE
LC0015 warns about "Record MyTable" instead of "TableData MyTable"

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#128]
Here's another thing I found when using LC0015:

In the warning for LC0015 it prints `warning LC0015: The application object Record My Table is not covered by any permission set in the extension.` when the TableData for the table is not included in any PermissionSet.

I would suggest to change the warning to `warning LC0015: The application object TableData "My Table" is not covered by any permission set in the extension.`

So two changes:
1. TableData instead of Table (if it's not the Table that we mean, if #127 is implemented ;-))
2. Add double quotes around the object name. This would make it easier to copy & paste the warnings and generate the missing permissions in a PermissionSet object. 

Now I'm done adding issues for today. ;-)
Keep up the good work and have a great weekend!

**Comment by StefanMaron** [comment]
Should be fixed in the latest prerelease

**Comment by jwikman** [comment]
I think this got broke with this update.

I do not get LC0015 when some tabledata is missing from the permissionset. 
I used PTE0004 before started to investigate LC0015, and PTE0004 detects the missing table.

**Comment by StefanMaron** [comment]
I removed tabledata because it is covered by PTE

**Comment by jwikman** [comment]
😣
I'm building AppSource apps and was hoping that this rule would help me to stop abusing the PerTenantExtensionCop. (By disabling all rules except PTE0004)

**Comment by StefanMaron** [comment]
I dont see why the other rule would not be usefull aswell TBH

**Comment by jwikman** [comment]
> I dont see why the other rule would not be usefull aswell TBH

I'm not following here, what other rule do refer to?
If you mean PTE0004, the rule in itself is good.
But I don't like what I need to do to only activate that rule (since a lot of other PTE rules conflicts with AppSource Apps). I have a huge ruleset that disables all (and I mean ALL) possible PTEXXXX rules except PTE0004.
It just feels as a hack, so I was happy when I noticed that LC0015 solved this as well (except having a few strange behaviors 🙂). So now I'm back at not very happy again. 😉

**Comment by StefanMaron** [comment]
Well I just checked what other rule are in the PTE https://docs.microsoft.com/en-us/dynamics365/business-central/dev-itpro/developer/analyzers/pertenantextensioncop

And to me it seems like most of them also apply for appsource apps, not?

**Comment by jwikman** [comment]
No.
They are not intended for use with AppSource Apps, most will just give false errors/warnings.
I've requested PTE0004 to be ported to AppSourceCop, but it does not seem to be prioritized yet. (https://github.com/microsoft/AL/issues/6503)

And the idea on how to only enable PTE0004 comes from https://github.com/microsoft/AL/issues/6505

**Comment by StefanMaron** [comment]
Interesting. Then, I guess, I will re-enable tabledata.

**Comment by jwikman** [comment]
Thanks 👍

**Comment by StefanMaron** [comment]
Done in v0.23.2

**Comment by jwikman** [comment]
It now detects missing permissions on TableData, very nice!

But the issue first reported in #126 is still present: I get false positives on tables with `TableType = Temporary`

**Comment by StefanMaron** [comment]
Of course, my bad. It now only warns on TableType = Normal

**Comment by jwikman** [comment]
Works like a charm! 
Well done, thanks!

Now I just need to implement LinterCop in our pipelines so I can kick out the PerTenantExtensionCop from our AppSource apps. 👍
