### ISSUE TITLE
LC0016 - False positives

### ISSUE THREAD

**Issue by jwikman** [StefanMaron/BusinessCentral.LinterCop#166]
I'm creating this issue instead of leaving it as a comment in discussion #121, this makes it easer to keep track of it. :)

This rule have a couple of "false positives":
- [ ] If the SourceTable of a page is a system table (like the `Field` table), the field always has a caption, so no need to throw warnings here
- [ ] Caption on API objects (query and page). Captions should probably be added on fields, but not needed on object level. (this is how MS does it)

_Originally posted by @jwikman in https://github.com/StefanMaron/BusinessCentral.LinterCop/discussions/121#discussioncomment-2244128_

**Comment by StefanMaron** [comment]
Yes, thanks for moving this here.

**Comment by StefanMaron** [comment]
should be fixed

**Comment by jwikman** [comment]
Actually this change made this worse. 😲
Now LC0016 appears on every control, even if the Caption property is available or not. 
It now seems as if this rule only thinks it's ok if the caption is directly on the control.

Any clues on what's wrong?

Sample with `Field` as SourceTable:
![image](https://user-images.githubusercontent.com/23032645/156898373-afdb71c2-2554-417c-9536-e073c3580a88.png)

`Area`
![image](https://user-images.githubusercontent.com/23032645/156898402-d90b8fa2-4d17-4456-8065-73439cc35759.png)

Own table as SourceTable:
![image](https://user-images.githubusercontent.com/23032645/156898423-6fc20014-5c71-420a-b550-3208513ad670.png)

**Comment by StefanMaron** [comment]
I forgot to add one single `else` so the `if` becomes a `else if` 😅

Should work now

**Comment by jwikman** [comment]
Those small words can make a huge difference! 😂

The the last change removed all my LC0016 warnings. 👍

BUT, there seem to be some issue with the deployment of the dll. I had to manually download it from https://github.com/StefanMaron/BusinessCentral.LinterCop/actions/runs/1940593110. 
I only get v0.24.6 when downloading through VSCode. It seems to be no Release created for v0.24.7 either (https://github.com/StefanMaron/BusinessCentral.LinterCop/releases). 
Maybe it was intended in this case, but thought I'd mention it anyway.

**Comment by StefanMaron** [comment]
Should work now.

I set up the pipelines to automatically create releases but they are marked as `draft`.
Just for me to be able to review before it gets rolled out.

**Comment by jwikman** [comment]
I see.

Yes, it works now. 👍

**Comment by epernst** [comment]
Has this one been fixed?
Still getting false warnings, whenever I put in the table (Rec) :
![image](https://user-images.githubusercontent.com/5236163/160103584-95da4a64-dd9d-4807-bb98-49510246277e.png)

**Comment by StefanMaron** [comment]
Has the field on the table a caption?
And do you use the current AL Language version or the version for BC20? (AL Language 9.*)

**Comment by epernst** [comment]
Yes the field has a caption. And we are using the latest AL Language version (on BC 14.29).
I got the error when running my pipeline today, on code that has not been changed since it ran fine last week.

**Comment by StefanMaron** [comment]
Is the pipleline using the vsix from artifacts or from the marketplace?
I released a new version this week, which explains why it worked last week.
