### ISSUE TITLE
AL Language Extension Version: v14.0.1002061 (pre-release) - Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.ParameterListSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VarSectionSyntax'.

### ISSUE THREAD

**Issue by pri-kise** [StefanMaron/BusinessCentral.LinterCop#606]
The latest version of the LinterCop Preview version seems to have problems with the preview version of the AL Language extension.
```
System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.ParameterListSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VarSectionSyntax'.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.FindLocalVariables(SyntaxNode node)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

AL Language Extension Version: v14.0.1002061 (pre-release)

**Comment by pri-kise** [comment]
I've downloaded the latest LinterCop DLLs.

I copied the DLL `BusinessCentral.LinterCop.AL-14.0.1002061.dll` to `BusinessCentral.LinterCop.dll`

I closed all VS Code sessions.

Is there anything I did wrong in the manual process to use the correct LinterCop Version?

**Comment by Arthurvdv** [comment]
I'm going to close this issue, where I believe it's resolved with the latest update of the LinterCop (combined with the VS Code extension) to handle this.

**Comment by pri-kise** [comment]
@Arthurvdv can you maybe reopen this issue.
This issue is back for our NextMajor Pipelines:

VSIX: 14.0.1070882

**Comment by pri-kise** [comment]
@Arthurvdv I must have been blind.
The error looks pretty similiar, but is a little bit different:
```
Unhandled exception. Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.VarSectionSyntax' to type 'Microsoft.Dynamics.Nav.CodeAnalysis.Syntax.GlobalVarSectionSyntax'.
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.FindGlobalVariables(SyntaxNode node)
   at BusinessCentral.LinterCop.Design.Rule0044AnalyzeTransferFields.AnalyzeTransferFields(OperationAnalysisContext ctx)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
The function `FindGlobalVariables` instead of the function `FindLocalVariables` is the problem this time.

**Comment by Arthurvdv** [comment]
@pri-kise , I see now I added an LC0000 for the `FindLocalVariables`  the last time, where I was hoping for a small code sample to reproduce this error. In the pre-release version of the LinterCop I now also added this to the `FindGlobalVariables`.

Can you see if you have a LC0000 diagnostic on this? Would be great if you could share a small code sample on this.

**Comment by pri-kise** [comment]
@Arthurvdv thanks for your fast response.
I tried to reproduce the error and now it's gone.

During my research I found out, that we are having problems with our Download Script.
We currently only Download the normal BCLintercopp.dll and not the BCLinterCop.next.dll. Therefore the next DLL wasn't up to date.
After manually replacing the next DLL the error was gone.

I will close this issue for now. Thanks for you help.

**Comment by Arthurvdv** [comment]
No problem! I'm going to remove these LC0000 diagnostic for now (to reduce the Try/Catch).

P.S. I'm thinking of obsoleting the `BusinessCentral.LinterCop.next.dll` artifact in the future, because this is the same as the `BusinessCentral.LinterCop.AL-PreRelease.dll`.

**Comment by pri-kise** [comment]
a good to know. I wasn't aware of that.
Hopefully not in the next months during summer holdiay, because we're still relying on this artifact.

**Comment by Arthurvdv** [comment]
Absolutely not during the holiday season (juli/august), probably somewhere 2026 I guess.

I’ve posted an issue to be made this generally known: https://github.com/StefanMaron/BusinessCentral.LinterCop/issues/709
